### ISSUE TITLE
Skill / Approach name won't get to the 'sendToVTT' function

### ISSUE THREAD

**Issue by rokunin** [sheibeck/fcs#112]
When saving Skills or Approaches for the Adversaries the names of the items won't get to the AdversaryList's <p id> param. 
It's everytime just an index int value of the items.skills.
Therefore it can't get the name from the 'id' to the function.

Probably, the problem is in this line of code, where it  could possibly be setting the 'type: int' value instead of the actual 'string':
https://github.com/sheibeck/fcs/blob/160da01962a8223f23855fcc9f3cad059de979b1/src/pages/AdversaryList.vue#L77

**Comment by sheibeck** [comment]
Thank you for reporting this.

Can you you tell me what you are attempting to do and give me some
additional context? What adversary are you using (url)? What virtual table
are you using, scene builder or roll20?

Part of the issue with adversaries is that you can put the skill numbers
and names in various locations, so I have to do some guessing at which
field is the name and which is the number. So, knowing the format of your
adversary is important to fixing this.

Thanks.

**Comment by rokunin** [comment]
Thank you for your attention (and huge thanks for the software, it's great!)
So  what I attempted to do was to add skills to my adversaries and to use them for my roll20 game sessions.
The adversary edit page suggests different options for the skills.
I'll take the Add Skill option as an example for the sake of simplicity (all other options work the same for me).

**Failed case**
Try:
- https://monosnap.com/file/WxxltVxiRZ45b7fPiUDP2cpFOEPB9T
- save
- go to https://fatecharactersheet.com/adversary/Mj1_w2zWi/test-npc
- click"+"

Result:
- https://monosnap.com/file/ZCURu3KvAjI4LyPnezj8ZeFXBHN0q3

Log:
- https://monosnap.com/file/tIl8dDPiQR1CVC3BMXcO1qMJzXjLOa

**Successful case (but looks hacky*
Try:
- https://monosnap.com/file/wftE4W8IN1auAGs4H3epHxSzV0HIDA
- save
- go to https://fatecharactersheet.com/adversary/Mj1_w2zWi/test-npc
- click "+"

Result: 
- https://monosnap.com/file/7aRJ1s5VLtmLTbyKhINgWmROvtgW5Y

Log:
- https://monosnap.com/file/goZEg5Z7upKPgB8iCQE9h9ByDPGU1E

**Comment by sheibeck** [comment]
Thank you for all the details. Much appreciated. I'll get a fix in here
soon as I can.

**Comment by sheibeck** [comment]
This issue is fixed with version 2.4.4. Please let me know if you still experience issues with this.

At some point, I need to rewrite the Adversary Input form. I must've missed this when I started making some steps in that direction. Thanks for finding it and taking the time to research. That helped a lot!

And, side note, I shouldn't be letting anyone type skills without putting in a skill modifier somewhere. So, the hacky way you discovered to put multiple skills but a blank input is still possible, but, will still show some jenky results. However, the original issues should be fixed!

**Comment by rokunin** [comment]
>>At some point, I need to rewrite the Adversary Input form. I must've missed this when I started making some steps in that direction. 
If you will have any easy-to-do tasks, I could probably help.
I have zero experience in vue, but I coded some stuff years ago using node.js and some template / build engines and partly it looks close to same.

**Comment by sheibeck** [comment]
I appreciate the offer! I'll keep that in mind as I work through some of this stuff. I've had to back-burner this project a bit just because life right now.
