### ISSUE TITLE
Wrong Adversary name when sending data to the roll20

### ISSUE THREAD

**Issue by rokunin** [sheibeck/fcs#115]
**Failed case**
Try: 
- go to the adversaries list
- tick the "Show only my adversaries" at https://fatecharactersheet.com/adversary
- choose certain adversary: https://monosnap.com/file/Ctc0WMr6UvaXa0kG4sav8g4ZESlA5Z
- click icons for the skills / aspects / stunts

Result:
- https://monosnap.com/file/pDSK8JZfhojXKeEeoVYGk9OaU2kuG8

**Successful case**
Try:
- go to the adversaries list
- open certain adversary: https://fatecharactersheet.com/adversary/Mj1_w2zWi/test-npc
- click icons for the skills / aspects / stunts

Result:
- https://monosnap.com/file/XSomw9osoRxvuUCOix1uiEnW2JTwow

**Comment by sheibeck** [comment]
Wow. That's definitely not right. I'll do some digging. Thanks!

**Comment by sheibeck** [comment]
This issue is now fixed in version 2.4.5.
