### ISSUE TITLE
Can't join a scene, create a new character or view my scenes.

### ISSUE THREAD

**Issue by camphi** [sheibeck/fcs#119]
Hi,
I created a new account to test a scene with a test player and he can't join.
With the new account I tried to create a fate accelerated character but when I save I get an error.
I checked with the debugger and I get an error 400 with the post.
I tried to join a scene but I never get the answer from the server.
When I click on "My Stuff" -> "My Scenes" I get an error 400.

I created the account using an alias of my email with a plus sign (+).

Tell me if you need anything from me.
Thank you

**Comment by sheibeck** [comment]
Could you tell me what browser you're using? I want to rule out browser issues first.

It IS possible that it's your email address because we don't have "usernames", so I try to guess at a name based on the portion of your email that comes before the @ sign. With the + in your username it could be causing issues, but I'll take a look.

Do you have issues in any other part of the system?

**Comment by camphi** [comment]
Hi,
I am on my chromebook, so chrome.

Tonight I can create character and update them but I still can't join the scene from my main account.

I can see sentry tagging some errors here are the Event ID : 
- 3914f03248a24a9ab776f137ed262a56
- 3470ae67c7d246a0963d45be87a28865
- fdecbe23fa01494ab3559cde15856a49

I can see the websocket sending one heartbeat to the server but I never received anything back.

I would be happy to help if you want to do a live testing session.

**Comment by sheibeck** [comment]
There's something going on with my peerjs server. It's apparently not letting any joins. I'm working on finding a resolution. Thanks for bringing this to my attention.

**Comment by sheibeck** [comment]
Can you give this a try again. I found an issue where the game peerId was not being saved, so the player connections didn't know which game to connect to. When you launch a game now, it should save your gameId properly and players will now connect. 

If you could try it with an existing scene and with a new scene and report your findings it would be much appreciated!! 

And thank you for finding this issue. No one had said anything and I was wondering why no one was really using the game table.

**Comment by camphi** [comment]
It's working! From an already created scene and a new one. Thank you.

The only bug I can see is the selector with the everyone and player names is not working for me.
I tried to send a message to myself only from the player's side and then from the DM's side and everyone can still see the message.

**Comment by sheibeck** [comment]
Awesome. I'll check into the messages selector. Please let me know if
(when?) You find other issues and I'll fix 'em up.
