### ISSUE TITLE
Account in limbo when confirmation mail is not received

### ISSUE THREAD

**Issue by emanciperingsivraren** [sheibeck/fcs#158]
I have registered an account, but I never received a confirmation email (mail that is sent to confirm email address).

Now I can not 
* log in
* register
* reset password

Maybe the site could resend the confirmation mail?

**Comment by sheibeck** [comment]
Actually, I just made an enhancement to the website. If you go to https://fatecharactersheet.com/login, you can enter your email and click the link on the bottom that reads **Resend your confirmation email?**

Give me a shout if that works. Thanks for bringing this to my attention.

**Comment by emanciperingsivraren** [comment]
That was fast :)
I have tried the new feature, and a green box informs me that the mail has been sent, but I don't get any new ones. I have whitelisted fatecharactersheet.com and turned off graylisting, I does not help.
What to do?

Can I send my adress privatly?

**Comment by sheibeck** [comment]
Hmm, not sure why it wouldn't reach you, but sometimes email can be finnicky. Feel free to send me your email address and I can manually do it for you. You can email it to sheibeck@gmail.com.

Oh, and the email comes from amazoneses, so the domain you could also try whitelisting is amazonses.com. But, I'm happy to manually do this for you as well.
