### ISSUE TITLE
Request for Dreden character sheet

### ISSUE THREAD

**Issue by DavidNovo** [sheibeck/fcs#170]
A character sheet for the Dresden game would be great.  Not Dresden Accelerated, but the original version of the Dresden Files that uses Fate Core System.

**Comment by sheibeck** [comment]
Hi, David. I appreciate the request. Could I recommend you try using the Fate Anything sheet and customizing it?

The original Dresden Files Our World game was actually published in 2010, three years before Fate Core. 

The sheet doesn't have anything crazy on it, so you could get pretty close by customizing the Fate Anything sheet. I don't have plans to support older versions of fate.
