### ISSUE TITLE
Unable to open character sheets

### ISSUE THREAD

**Issue by geesloper** [sheibeck/fcs#172]
Attempting to open a specific character sheet sits on 'Loading', then after 30 seconds or so, then displays a red box with the text [Object object]. 

If I try to open 'My Characters', I get the message "You have not created any characters."

Testing: Tried it in Incognito mode (in case it was a browser extension on my end) - no luck.

**Comment by geesloper** [comment]
Seems to have come right on its own (phew!)

**Comment by sheibeck** [comment]
Glad it worked out!
