### ISSUE TITLE
Fate Point Tracking

### ISSUE THREAD

**Issue by ChrisDangerRose** [sheibeck/fcs#28]
Add the capability to track Fate Points ot the Character sheet

**Comment by sheibeck** [comment]
Hi, Chris. Which Sheet are you using? Some sheets have fate point tracking, and others don't because I based my sheets on the official character sheets.

**Comment by ChrisDangerRose** [comment]
I'm an idiot.

I work in IT Support. I sat looking at the case as I was creating it wondering "What information did I miss?"

It's the FATE Condensed sheet.

Thanks

**Comment by sheibeck** [comment]
No problem. Thanks for the update. 😃

**Comment by sheibeck** [comment]
This is now in production.
