### ISSUE TITLE
Character Name on Browser tab

### ISSUE THREAD

**Issue by ChrisDangerRose** [sheibeck/fcs#29]
To enable easier navigation when multiple characters are on in one browser sessions, set the tab title to the character name

**Comment by sheibeck** [comment]
Thanks Chris. This (and your other issue) are complete. I'm just waiting on some testing because I'm deploying a really big feature set. Should sometime in the next couple of weeks.

**Comment by ChrisDangerRose** [comment]
Very cool. Look forward to it!

**Comment by ChrisDangerRose** [comment]
Brilliant!

Can't wait to see what else is rolling out.

Thanks,

-Chris

**Comment by sheibeck** [comment]
This is now in production.
