### ISSUE TITLE
[feature request]Support Fate Condensed

### ISSUE THREAD

**Issue by Enturk** [sheibeck/fcs#31]
[Fate Condensed](https://fate-srd.com/fate-condensed/introduction) is the next edition of Fate. Of note, it went to one-point stress boxes (relevant skills give you more stress boxes now). It would be nice if the character sheet supported this.

**Comment by Enturk** [comment]
[This appears to already have been implemented](https://fatecharactersheet.com/charactersheet/fate-condensed). Can it be connected to Roll20?

**Comment by Enturk** [comment]
I'm guessing it will be implemented. Apologies for the clutter.

**Comment by sheibeck** [comment]
It's implemented already. You do have to have a subscription to see/use the Roll20 functionality. Let me know if you additional info, I'm happy to help! Thanks for submitting tickets, it helps a ton to get feedback from the community.
