### ISSUE TITLE
[Feature Request] Custom stress tracks

### ISSUE THREAD

**Issue by Enturk** [sheibeck/fcs#33]
Fate of Cthulhu has a corruption stress track, and I use Resource and Organization stress tracks to track those things. Some games only use one stress track. It would be nice to be able to edit, add and delete stress tracks.

**Comment by roypenrod-ohn** [comment]
Related to this, we also need to be able to edit the number of stress boxes per track.

The "Hunters of Alexandria" World of Adventure, for example, starts with 3 stress boxes and the "Former Slave" Extra can grant 2 more stress boxes.  

The Fate Core sheet is hard-coded for 4 physical stress boxes, so it doesn't work for either the baseline or the "Former Slave" extra.
