### ISSUE TITLE
Scene Builder

### ISSUE THREAD

**Issue by sheibeck** [sheibeck/fcs#36]
Ability to run a game using objects from the system. Allow for zones, aspects, etc.

**Comment by Enturk** [comment]
Not sure if this is already or not, but it would be nice to be able to add images to a scene. If we're playing online, might as well use the images that are available on teh interwebz to help create atmosphere.

**Comment by Enturk** [comment]
Ignore my request above. I just noticed that you can already do this.

**Comment by sheibeck** [comment]
I'm glad you're giving the system a try. I've been pushing fixes all day today as I've been finding bugs. So, if you see other stuff keep sending me a ticket, please! :D

**Comment by esaiander** [comment]
It would be great to add images that aren't scene backgrounds (for showing NPCs that don't have sheets) . The images are dimmed when added as a background and the thumbnails too small to have to impact
