### ISSUE TITLE
Unable to Save a Character

### ISSUE THREAD

**Issue by amazingrando** [sheibeck/fcs#4]
Browser & OS info: https://mybrowser.fyi/report/5e782c381f96200015bed0eb
No ad blockers running.

Video walk through of two failed attempts to create a character: https://www.loom.com/share/addfe58b747a4a1d97549de4132e0f9b

**Comment by sheibeck** [comment]
Looks like Firefox with Mac combination is the issue here. I'll work on a way to test on a mac so I can fix this up.

**Comment by amazingrando** [comment]
@sheibeck I tested this in FF, Safari, and Chrome on a mac, so the issue is across browsers.

**Comment by sheibeck** [comment]
I can actually see your records in the database. It looks like there's an issue with AWS and some user accounts. I have a friend who signed up with 2 different accounts (one gmail, one icloud), and he can use the system normally with his gmail account, but his icloud account has the same issue you are reporting, and it's not just on the MAC but on Windows, too. 

I'm looking into it. This the first time I've seen it, and it's a weird one. Thanks for catching it :D

**Comment by amazingrando** [comment]
I am weirdly a QA master. I seem to have great "luck" at finding issues. :)

**Comment by sheibeck** [comment]
I found the issue. I'm using table scans in dynamodb and I've finally reached enough records that I have to do more than one scan to pickup all the records. I'm working on a refactor here and substituting queries where I can.

**Comment by amazingrando** [comment]
Glad to hear that you found the issue. 👍

**Comment by sheibeck** [comment]
Thanks again. This issue should be resolved now. Please let me know if you see other issues!
