### ISSUE TITLE
Add Pronouns field

### ISSUE THREAD

**Issue by aravol** [sheibeck/fcs#49]
Per [recent changes in the official character sheets](https://twitter.com/EvilHatOfficial/status/1283455245729710080?s=20), it seems fitting to add a Pronouns field for characters

**Comment by sheibeck** [comment]
Thank you for the suggestion. I will put this on the list. I've had other suggestions that I feel fall in the same category (i.e add a field for <insert field name here>), so I'll look for a place to integrate these that I think will work with my vision for sheets.

However, I feel that anything like pronoun, race, ethnicity, language, religious affiliation, etc should be encapsulated in your character's aspects if they are very important to your character. I believe that is the purpose of aspects and how they define who your character is.
