### ISSUE TITLE
[Feature Request] Add or delete Aspects 

### ISSUE THREAD

**Issue by roypenrod-ohn** [sheibeck/fcs#59]
Right now, Aspects are hard-coded into the Fate Core character sheet.

There are five and only five.

But Fate Core is more flexible than that.  The book mentions you can have more than that even though it's not always recommended.

And Evil Hat's own "World of Adventure" series supports that.

Take a look at "Hunters of Alexandria".

If you take the "Former Slave" Extra, you are given an additional Trouble aspect: "Former Slave".  

Right now, I can't add that Aspect to the character because there's no way to add a sixth Aspect.

Just treat Aspects as an array of Aspect objects and let the users decide how many they need on their sheet.

**Comment by sheibeck** [comment]
I've gotten several requests to allow for customizing the sheets. I'm putting this in the list here. I'll be looking to tackle customizations after I release the VTT. Thanks for the request.
