### ISSUE TITLE
Character Sheet information disappeared 

### ISSUE THREAD

**Issue by ghoinghost** [sheibeck/fcs#6]
When I open my character sheet, all of the information has disappeared, and it won't let me reapply my skills. This is a problem with my friend's information as well. The same thing happened, we opened his character sheet and all of his information was gone.

**Comment by buttonpushertv** [comment]
Having the same issue. I was checking out fatecharactersheets.com for possible use in an online game. I had started to work on a character, saved them half way through, and tried opening the 'Share' link in a different browser window. When the sheet loaded, all the fields were blank. Also attempting to re-open the sheet in the same browser window where I had created it gave me the same blank result.

This is the sheet: https://fatecharactersheet.com/character/fate-core-custom/8de960fc-95e3-41db-8ce4-1ae600910031/darcy

And on the 'My Chracters' sheet, I can see it listed. And it has some of the info I had placed onto the sheet shown, so I think it has stored the data...somewhere & it's not getting loaded back in on reload/share of the sheet.

**Comment by sheibeck** [comment]
Oh man, really sorry about that. Thank you for letting me know! I just fixed the issue and it looks like the data is showing up again. I had some sort of corrupted file issue going on. Please let me know if you can see your characters once again!
