### ISSUE TITLE
Missing a Privacy Policy

### ISSUE THREAD

**Issue by amazingrando** [sheibeck/fcs#7]
You may want to consider adding a privacy policy, as well as a GDPR box since you are managing accounts. I use https://www.iubenda.com/en/ on the Fate SRD.

**Comment by sheibeck** [comment]
That's a good idea. Thanks for the resource. I'll add this in.

**Comment by sheibeck** [comment]
Privacy policy added. Honestly, I couldn't justify spending $9 a month for the GDPR stuff. Maybe at some point I will add that in, but have to weight time/money vs this being a side gig.

**Comment by amazingrando** [comment]
@sheibeck I don't blame you. I don't have one for any of my SRD sites.
